//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sample.rc
//
#define IDC_MYICON                      2
#define IDJUMP                          3
#define IDGOTO                          4
#define IDPOKE                          5
#define IDD_SAMPLE_DIALOG               102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_SAMPLE                      107
#define IDI_SMALL                       108
#define IDC_SAMPLE                      109
#define IDC_ACCEL                       109
#define IDS_FAIL_INITDI                 111
#define IDS_FAIL_LOAD                   112
#define IDS_LOAD_FILTER                 113
#define IDS_SAVE_FILTER                 114
#define IDS_FAIL_WINPFIELD              115
#define IDS_FAIL_INITDD                 116
#define IDS_FAIL_FEWBITCOUNT            117
#define IDS_FAIL_LOADCORRUPT            118
#define IDS_FAIL_INITWND                119
#define IDS_CATEGORIES                  120
#define IDS_CATEGORIES2                 121
#define IDS_CATEGORIES3                 122
#define IDS_CATEGORIES4                 123
#define IDS_CATEGORIES5                 124
#define IDS_MSG_PETERZOLI               125
#define IDS_MSG_SZEGVARIS               126
#define IDS_MSG_IAINSCURRAH             127
#define IDR_MAINFRAME                   128
#define IDS_MSG_WOLFPETER               128
#define IDD_DEBUG                       129
#define IDS_MSG_CSERNAZS                129
#define IDS_MSG_SZVERA                  130
#define IDD_JUMP                        131
#define IDD_DIALOG_SPEED                134
#define IDD_DIALOG_POKE                 135
#define IDD_KEYBOARD                    139
#define IDR_ROM                         142
#define IDB_ZXSPEC                      150
#define IDSTEP                          1000
#define IDC_LIST                        1001
#define IDC_RADIO_Z                     1002
#define IDC_RADIO_S                     1003
#define IDC_RADIO_F5                    1004
#define IDC_RADIO_H                     1005
#define IDC_RADIO_F3                    1006
#define IDC_RADIO_PV                    1007
#define IDC_RADIO_N                     1008
#define IDC_RADIO_C                     1009
#define IDC_REGBC                       1010
#define IDC_REGDE                       1011
#define IDC_REGHL                       1012
#define IDC_REGAF                       1013
#define IDC_REGBC2                      1014
#define IDC_REGDE2                      1015
#define IDC_REGHL2                      1016
#define IDC_REGAF2                      1017
#define IDC_REGI                        1018
#define IDC_REGPC                       1019
#define IDC_REGSP                       1020
#define IDC_REGR                        1021
#define IDC_IM                          1022
#define IDC_IFF                         1023
#define IDC_REGIX                       1024
#define IDC_REGIY                       1025
#define IDC_HALT                        1026
#define IDC_HALT_D_HALT                 1026
#define IDC_EDIT_JUMP                   1027
#define IDINT                           1027
#define IDC_LIST_MEM                    1029
#define IDC_EDIT_SPEED                  1032
#define IDC_EDIT_FRAME                  1033
#define IDC_ST                          1033
#define IDC_EDIT_FLASH                  1034
#define IDC_EDIT_ADDR                   1034
#define IDC_EDIT_VAL                    1035
#define IDC_RADIO_DEC                   1037
#define IDC_RADIO_HEX                   1038
#define IDC_COMBO_CAT                   1039
#define IDC_LIST_ITEMS                  1040
#define IDC_STATIC_DESC                 1042
#define IDC_BT_PETERZOLI                1043
#define IDC_IMG_ZXSPEC                  1048
#define IDC_STATIC_ABOUT_1              1049
#define IDC_STATIC_ABOUT2               1050
#define IDC_STATIC_ABOUT3               1051
#define IDC_STATIC_ABOUT4               1052
#define IDC_STATIC_ABOUT5               1053
#define IDC_STATIC_D_REGS               1054
#define IDC_STATIC_D_FLAGS              1055
#define IDC_STATIC_D_BC                 1056
#define IDC_STATIC_D_DE                 1057
#define IDC_STATIC_D_HL                 1058
#define IDC_STATIC_D_AF                 1059
#define IDC_STATIC_D_IX                 1060
#define IDC_STATIC_D_I                  1061
#define IDC_STATIC_D_PC                 1062
#define IDC_STATIC_D_IM                 1063
#define IDC_STATIC_D_IFF                1064
#define IDC_STATIC_D_BC2                1065
#define IDC_STATIC_D_DE2                1066
#define IDC_STATIC_D_HL2                1067
#define IDC_STATIC_D_AF2                1068
#define IDC_STATIC_D_IY2                1069
#define IDC_STATIC_D_R2                 1070
#define IDC_STATIC_D_SP                 1071
#define IDC_STATIC_POKE_ADDR            1072
#define IDC_STATIC_POKE_VALUE           1073
#define IDC_STATIC_SPEED_CPU            1074
#define IDC_STATIC_SPEED_RATE           1075
#define IDC_STATIC_SPEED_FF             1076
#define IDC_STATIC_JUMP_LAB             1077
#define IDC_STATIC_KBA_F1               1078
#define IDC_STATIC_KBA_F2               1079
#define ID_FILE_RESET                   32771
#define ID_OPTIONS_VIEW_1X1             32772
#define ID_OPTIONS_VIEW_2X2             32773
#define ID_OPTIONS_VIEW_FULLSCREEN      32774
#define ID_FILE_DEBUG                   32775
#define ID_FILE_STEP                    32776
#define IDA_FILE_STEP                   32776
#define ID_FILE_LOAD                    32777
#define ID_OPTIONS_SPEEDTEST            32778
#define ID_OPTIONS_SETSPEED             32779
#define ID_OPTIONS_VIEW_BORDER          32780
#define ID_FILE_SAVE                    32781
#define IDA_FILE_LOAD                   -32754
#define IDA_FILE_RESET                  -32752
#define IDA_FILE_DEBUG                  -32751
#define ID_OPTIONS_VIEW_INTERLACE       32786
#define ID_OPTIONS_VIEW_NONINTERLACE    32787
#define ID_TOGGLE_FULLSCREEN            32788
#define ID_OPTIONS_SPEED_REAL           32789
#define ID_OPTIONS_SPEED_SYNC           32790
#define ID_OPTIONS_SPEED_FULL           32791
#define ID_HELP_DESC                    32792
#define ID_HELP_KEYBOARD                32793
#define ID_FOCUSTOKINF                  32794
#define ID_FILE_SAVEAS                  32795
#define IDC_STATIC                      -1
#define ID_OPTIONS_SOUND                65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
